server:
  port: 8080
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8084

spring:
  profiles: prod
#person:
##  last-name: zhangsan
#  lastName: 张三
#  age: 18
#  boss: false
#  birth: 2020/02/02
#  maps: {k1: v1, k2: v2}
#  lists:
#    - lisi
#    - wangswu
#  dog:
#    name: 小狗

#    age: 12